### ISSUE TITLE
PyPDF failed to extract text from some PDFs. Maybe slate3k could be the PDF extractor lib?

### ISSUE THREAD

**Issue by tiagostutz** [flaviostutz/datascience-tools#1]
Hi!
I had some issues extracting PDF texts with `PyPDF`. Turns out that it was extracting only the footer text of the document. I tried to fix it, but with no lucky. Then I tried `slate3k` and it worked like a charm.

Do you think there is space for it on datasciente-tools?

**Comment by flaviostutz** [comment]
Sure! Add it to both CPU and GPU Dockerfiles.
